equivalent_blocks = {
    0x00: "air",
    0x01: "stone",
    0x02: "brick_block",
    0x03: "andesite",
    0x04: "oak_log",
    0x2A: ("oak_log", "oak_log"),
    0x06: "oak_planks",
    0x07: "dirt",
    0x0A: "oak_leaves",
    0x0B: "glass",
    0x0C: ("normal_stone_slab", "slab"),
    0x0D: "poppy",
    0x0E: "dandelion",
    0x10: "birch_log",
    0x2B: ("oak_log", "birch_log"),
    0x08: "grass_block",
    0x15: ("oak_slab", "slab"),
    0x16: ("andesite_slab", "slab"),
    0x14: "birch_leaves",
    0x17: "cobblestone",
    0x18: "sand",
    0x19: "gravel",
    0x1A: "brown_mushroom",
    0x1B: "red_mushroom",
    0x1C: "brown_concrete_powder",
    0x1D: "reeds",
    0x1F: ("smooth_stone_slab", "slab"),
    0x1E: "smooth_stone",
    0x20: ("cobblestone_slab", "slab"),
    0x2E: "white_wool",
    0x2F: "light_gray_wool",
    0x30: "gray_wool",
    0x31: "black_wool",
    0x32: "red_wool",
    0x33: "orange_wool",
    0x34: "yellow_wool",
    0x35: "lime_wool",
    0x36: "green_wool",
    0x37: "cyan_wool",
    0x38: "light_blue_wool",
    0x39: "blue_wool",
    0x3A: "purple_wool",
    0x3B: "magenta_wool",
    0x3C: "pink_wool",
    0x3D: "brown_wool",
    0x3E: "iron_block",
    0x3F: "gold_block",
    0x40: "crimson_slab", # Beds are too complex
    0x41: "crimson_slab", # 
    0x4C: "short_grass",
    0x4D: "deadbush",
    0x46: "packed_ice",
    0x51: "obsidian",
    0x55: "cherry_leaves",
    0x56: "melon_block",
    0x57: "pumpkin",
    0x58: "hay_block",
    0x59: ("hay_block", "hay"),
    0x5A: ("birch_trapdoor", "carpet"),
    0x68: "birch_planks",
    0x5B: ("spruce_trapdoor", "carpet"),
    0x6E: "spruce_planks",

    0x29: "snow",
    0x24: "snow",
    0x25: "snow_layer",
    0x21: "bookshelf",
    0x23: "netherreactor", # No TV in MC
    0x26: "barrel",
    0x22: "netherreactor", # No TV in MC
    0x28: ("furnace", "furniture"),
    0x27: ("furnace", "furniture"),
    0x4A: ("crafting_table", "furniture"),
    0x4B: ("chest", "furniture"),
    0x2C: "redstone_lamp",
    0x2D: "sea_lantern",

    0x0F: ("ladder", "ladder"),
    0x12: ("torch", "torch"),
    0x42: "oak_fence",
    0x47: "wooden_door",
    0x43: ("wooden_door", "door"), # Top door
    0x4E: ("fence_gate", "gate"),
    0x52: "iron_door",
    0x4F: ("iron_door", "door"), # Top door
    0x50: ("trapdoor", "trapdoor"), 

    0x53: ("brick_slab", "slab"),
    0x5C: "mossy_cobblestone",
    0x5D: ("mossy_cobblestone_slab", "slab"),
    0x5F: "smooth_sandstone",
    0x60: ("smooth_sandstone_slab", "slab"),
    0x62: "sandstone",
    0x63: ("sandstone_slab", "slab"),
    0x65: "stone_bricks", 
    0x66: ("stone_brick_slab", "slab"),
    0x69: ("birch_slab", "slab"),
    0x6B: "jungle_planks",
    0x6C: ("jungle_slab", "slab"),
    0x6F: ("spruce_slab", "slab"),

    0x6A: ("birch_stairs", "stairs"),
    0x6D: ("jungle_stairs", "stairs"),
    0x70: ("spruce_stairs", "stairs"),
    0x48: ("oak_stairs", "stairs"),
    0x49: ("stone_stairs", "stairs"),
    0x54: ("brick_stairs", "stairs"),
    0x5E: ("mossy_cobblestone_stairs", "stairs"),
    0x61: ("smooth_sandstone_stairs", "stairs"),
    0x64: ("sandstone_stairs", "stairs"),
    0x67: ("stone_brick_stairs", "stairs"),

    0x45: ("end_rod", "bulb"),
    0x44: ("end_rod", "bulb")
}

def get_equivalent_block(exploration_block: int):
    return equivalent_blocks.get(exploration_block, "unknown")